name: dio_builder
description: Dio builder is support plugin using dio, it helps to easy config dio in your project.
version: 3.0.4
homepage: https://github.com/georgesamirmansour/dioBuilder.git

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  dio_smart_retry: ^6.0.0
  chucker_flutter: ^1.8.2
  dio_http2_adapter: ^2.6.0
#  collection: ^1.18.0
dev_dependencies:
#  flutter_test:
#    sdk: flutter

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.gsamir.dio_builder.dio_builder
        pluginClass: DioBuilderPlugin
      ios:
        pluginClass: DioBuilderPlugin
      linux:
        pluginClass: DioBuilderPlugin
      macos:
        pluginClass: DioBuilderPlugin
      windows:
        pluginClass: DioBuilderPluginCApi
      web:
        pluginClass: DioBuilderWeb
        fileName: dio_builder_web.dart